language: ruby
before_script:
- git config --global user.email "travis-ci@sss-course"
- git config --global user.name "Travis-CI"
- npm install
- bower install
script: bundle exec roger release
branches:
  only:
  - master
env:
  global:
  - secure: l8BwGj2ihJkDfvM9ZrrKCGgmWlKyGYYe8uX+PJjyIY8/xJV/TjDDcOcBWzy3GD+1J9+U9bPcGFMklvjElUazSZ7OXwgYQ9gKhIbVibsql+A5HIcPjAvUGVAnMCueSExJGcN92mKtIm0wT/RZUnJDx+JJ4bLKOdSkxlcrQMzotIE=
